{#- See https://www.linode.com/docs/guides/linux-static-ip-configuration/#ubuntu-1804-and-2004 #}
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      {#- Disable automatic IP configuration via DHCP and Router Advertisement. #}
      {#- link-local is not set, meaning only IPv6 link-local addresses are enabled. #}
      {#- https://netplan.io/reference/#common-properties-for-all-device-types #}
      dhcp4: no
      dhcp6: no
      accept-ra: no
      addresses:
      {#- networkd seems to use the last IP as the primary IP (unspecified). Linode's documentation lists the SLAAC IP last, #}
      {#- but this causes networkd to prefer its default IPv6 block to our IPv6 /64 block. #}
      {#- https://bugs.launchpad.net/netplan/+bug/1766656 #}
      {#- https://manpages.ubuntu.com/manpages/focal/man5/systemd.network.5.html #}
      {#- https://www.linode.com/docs/guides/linux-static-ip-configuration/#ubuntu-1804-and-2004 #}
        {%- for address in pillar.network.netplan.get('addresses', []) %}
        - {{ address }}
        {%- endfor %}
        - {{ pillar.network.ipv4 }}/24
        {%- if 'ipv6' in pillar.network %}
        - {{ pillar.network.ipv6 }}/64
        {%- endif %}
      gateway4: {{ pillar.network.netplan.gateway4 }}
      gateway6: fe80::1
      nameservers:
        search: ['open-contracting.org']
        addresses: ['178.79.182.5', '176.58.107.5', '176.58.116.5', '176.58.121.5', '151.236.220.5', '212.71.252.5', '212.71.253.5', '109.74.192.20', '109.74.193.20', '109.74.194.20', '2a01:7e00::9', '2a01:7e00::3', '2a01:7e00::c', '2a01:7e00::5', '2a01:7e00::6', '2a01:7e00::8', '2a01:7e00::b', '2a01:7e00::4', '2a01:7e00::7', '2a01:7e00::2']
