[api]

[providers.docker]
  exposedByDefault = false

[providers.file]
  filename = "/etc/traefik/dynamic.toml"

[entryPoints]
  [entryPoints.https]
    address = ":443"
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.http]
      [entryPoints.http.http.redirections]
        [entryPoints.http.http.redirections.entryPoint]
          to = "https"
          scheme = "https"

[log]
  level = "INFO"

[certificatesResolvers.acmec.acme]
  email = "sysadmin@open-contracting.org"
  httpchallenge = true
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.acmec.acme.httpChallenge]
    entrypoint = "http"
