readonlyrest:
  # https://github.com/beshu-tech/readonlyrest-docs/blob/master/kibana.md#loading-settings-order-of-precedence
  force_load_from_file: True
  # https://github.com/beshu-tech/readonlyrest-docs/blob/master/actionstrings/action_strings_es7.10.1.txt
  access_control_rules:
    - name: Allow manage admin access over localhost
      groups:
        - ocpadmin
      x_forwarded_for:
        - "127.0.0.0/8"
        - "{{ pillar.network.ipv4 }}"
        {%- if "ipv6" in pillar.network %}
        - "{{ pillar.network.ipv6 }}"
        {%- endif %}
        {%- if "admin_ips" in pillar.elasticsearch %}
        {%- for ip in pillar.elasticsearch.admin_ips %}
        - "{{ ip }}"
        {%- endfor %}
        {%- endif %}
    - name: Allow the public group to search indices created by OCDS Index
      groups:
        - public
      indices:
        patterns:
          - "ocdsindex_*"
        must_involve_indices: True
      actions:
        - indices:data/read/search
      x_forwarded_for: ["0.0.0.0/0"]
    - name: Allow the manage group to manage indices created by OCDS Index
      groups:
        - manage
      indices:
        patterns:
          - "ocdsindex_*"
      actions:
        - indices:admin/create
        - indices:admin/get
        - indices:data/read/search
        - indices:data/write/bulk
        - indices:data/write/delete/byquery
        - indices:monitor/settings/get
      x_forwarded_for: ["0.0.0.0/0"]
  users: {{ pillar.elasticsearch.plugins.readonlyrest.users|yaml }}
