apiVersion: 1

datasources:
  - name: OCP Prometheus
    type: prometheus
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: {{ pillar.prometheus.prometheus.version }}
      httpMethod: "POST"
      manageAlerts: false
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: false
