#!/usr/bin/env bash
# Configures Salt for a non-root user.

set -euo pipefail

SSH_KEY_PATH=~/.ssh/id_rsa
SALT_SSH_KEY_DIR=salt-config/pki/ssh
REPO_DIR=$(pwd)

mkdir -p $SALT_SSH_KEY_DIR
ln -sf $SSH_KEY_PATH $SALT_SSH_KEY_DIR/salt-ssh.rsa
ln -sf $SSH_KEY_PATH.pub $SALT_SSH_KEY_DIR/salt-ssh.rsa.pub

echo "salt-ssh:
  config_dir: $REPO_DIR/salt-config
" > Saltfile

echo "# https://docs.saltproject.io/en/latest/ref/configuration/master.html#std-conf_master-file_roots
file_roots:
  base:
    - $REPO_DIR/salt/
# https://docs.saltproject.io/en/latest/ref/configuration/master.html#std-conf_master-pillar_roots
pillar_roots:
  base:
    - $REPO_DIR/pillar/
" > salt-config/master

mkdir -p salt-config/master.d
echo "# https://docs.saltproject.io/en/latest/ref/configuration/master.html#std-conf_master-cachedir
cachedir: $REPO_DIR/cache/
# https://docs.saltproject.io/en/latest/ref/configuration/master.html#ssh-log-file
ssh_log_file: $REPO_DIR/ssh_log
# https://docs.saltproject.io/en/latest/ref/configuration/master.html#std-conf_master-pki_dir
pki_dir: $REPO_DIR/salt-config/pki/
# https://docs.saltproject.io/en/latest/ref/configuration/master.html#file-roots
file_roots:
  base:
    - $REPO_DIR/salt/
# https://docs.saltproject.io/en/latest/ref/configuration/master.html#pillar-roots
pillar_roots:
  base:
    - $REPO_DIR/pillar/
# https://docs.saltproject.io/en/latest/ref/configuration/master.html#std-conf_master-user
user: $USER" > salt-config/master.d/localuser.conf
