#!/bin/bash
set -e

echo "------------------- deploy"
git checkout master
git pull origin master

echo "------------------- deploy/pillar/private"
cd pillar/private
git checkout master
git pull origin master
cd ../..

echo "------------------- deploy/salt/private"
cd salt/private
git checkout master
git pull origin master
cd ../..
