#!/bin/bash
# Ensures all repositories are on master and up-to-date.

set -xeuo pipefail

git checkout master
git pull --rebase origin master

cd pillar/private
git checkout master
git pull --rebase origin master
cd ../..

cd salt/maintenance
git checkout master
git pull --rebase origin master
cd ../..
