global:
  resolve_timeout: 5m

route:
  receiver: ocp-email
  routes:
    - receiver: ocp-email
      group_by:
        - alertname
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1d
      continue: True
    - receiver: rh-email
      group_by:
        - alertname
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1d
      continue: True

receivers:
  - name: ocp-email
    email_configs:
      - to: sysadmin@open-contracting.org
        from: noreply@noreply.open-contracting.org
        smarthost: {{ pillar.smtp.host }}:{{ pillar.smtp.port }}
        auth_username: {{ pillar.smtp.username }}
        auth_password: {{ pillar.smtp.password }}
        require_tls: {{ pillar.smtp.tls }}
        send_resolved: True
  - name: rh-email
    email_configs:
      - to: servers@robhooper.net
        from: noreply@noreply.open-contracting.org
        smarthost: {{ pillar.smtp.host }}:{{ pillar.smtp.port }}
        auth_username: {{ pillar.smtp.username }}
        auth_password: {{ pillar.smtp.password }}
        require_tls: {{ pillar.smtp.tls }}
        send_resolved: True
