[{{ user }}]
user = {{ user }}
group = {{ user }}
listen = {{ socket }}
listen.owner = {{ listen_user }}
listen.group = {{ listen_user }}
{%- set pm = pm|default('static') %}
pm = {{ pm }}
pm.max_children = {{ pm_max_children|default(10) }}
{%- if pm == 'dynamic' %}
pm.start_servers = {{ pm_start_servers|default(2) }}
pm.min_spare_servers = {{ pm_min_spare_servers|default(1) }}
pm.max_spare_servers = {{ pm_max_spare_servers|default(3) }}
{%- endif %}
{%- if pm_max_requests is defined %}
pm.max_requests = {{ pm_max_requests }}
{%- endif %}
php_admin_flag[log_errors] = on
php_admin_value[error_log] = /var/log/php-fpm/{{ name }}/{{ user }}.log
{%- if env is defined %}
{%- for key, value in env|items %}
{{ key }} = {{ value }}
{%- endfor %}
{%- endif %}
