# We set both PermitRootLogin and PasswordAuthentication for two reasons:
#
# - PermitRootLogin adds a layer of security in case PasswordAuthentication is toggled on.
# - While PermitRootLogin is set to "no" or "without-password", we can monitor it with our intrusion detection software.

PasswordAuthentication no
PermitRootLogin without-password
X11Forwarding no
