x-shared: &shared
  env_file: .env
  user: "{{ pillar.docker.uid }}:{{ pillar.docker.uid }}"
  restart: unless-stopped

x-django: &django
  <<: *shared
  image: "ghcr.io/open-contracting/{{ entry.image }}-django:latest"
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    # The right-hand path must match the settings.DATABASES default value in the CoVE repository.
    - {{ entry.host_dir }}/db:/data/db
    # The right-hand path must match the settings.MEDIA_ROOT default value in the CoVE repository.
    - {{ entry.host_dir }}/media:/data/media

services:
  web:
    <<: *django
    ports:
      - {{ site.port }}:8000
  cron:
    <<: *django
    profiles:
      - cron
  static:
    <<: *shared
    image: "ghcr.io/open-contracting/{{ entry.image }}-static:latest"
    ports:
      - {{ site.static_port }}:8080
    volumes:
      # The right-hand path must match the root directive of the default.conf file in the CoVE repository.
      - {{ entry.host_dir }}/media:/data/media
