services:
  backend:
    env_file: .env
    user: "{{ pillar.docker.uid }}:{{ pillar.docker.uid }}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    image: "ghcr.io/open-contracting/credere-backend:latest"
    ports:
      - {{ pillar.docker_apps.credere_backend.port }}:8000
