services:
  web:
    env_file: .env
    user: "{{ pillar.docker.uid }}:{{ pillar.docker.uid }}"
    image: "ghcr.io/open-contracting/credere-frontend:latest"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - {{ site.static_port }}:8080
    restart: unless-stopped
