services:
  frontend:
    env_file: .env
    user: "{{ pillar.docker.uid }}:{{ pillar.docker.uid }}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    image: "ghcr.io/open-contracting/credere-frontend:latest"
    ports:
      - {{ pillar.docker_apps.credere_frontend.port }}:8080
