x-shared: &shared
  env_file: .env
  user: "{{ pillar.docker.uid }}:{{ pillar.docker.uid }}"
  restart: unless-stopped

x-django: &django
  <<: *shared
  image: "ghcr.io/open-contracting/digitalbuying-django:latest"
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    # The right-hand path must match the settings.MEDIA_ROOT default value in digitalbuying.
    - {{ directory }}/media:/data/media
  depends_on:
    - redis

services:
  redis:
    image: rapidfort/redis-official:6.2-bookworm
    command: ["redis-server", "/redis.conf"]
    user: "{{ pillar.docker.uid }}:{{ pillar.docker.uid }}"
    restart: always
    healthcheck:
      test: redis-cli -h 127.0.0.1 ping | grep -q PONG
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - {{ directory }}/redis/data:/data
      - {{ directory }}/redis/redis.conf:/redis.conf
  web:
    <<: *django
    ports:
      - {{ site.port }}:8000
  cron:
    <<: *django
    profiles:
      - cron
  static:
    <<: *shared
    image: "ghcr.io/open-contracting/digitalbuying-static:latest"
    ports:
      - {{ site.static_port }}:8080
    volumes:
      # The right-hand path must match the root directive of the default.conf file in digitalbuying.
      - {{ directory }}/media:/data/media
