x-shared: &shared
  env_file: .env
  user: "{{ pillar.docker.uid }}:{{ pillar.docker.uid }}"
  restart: unless-stopped

services:
  web:
    <<: *shared
    image: "ghcr.io/open-contracting/pelican-frontend-django:latest"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
{#- The port is on `entry`, not `site`, because the frontend is not necessarily web-accessible. #}
      - {{ entry.port }}:8000
{%- if entry.get('reports') %}
    volumes:
      # The right-hand path must match the STORAGES default value in pelican-frontend.
      - {{ entry.host_dir }}:/data
  static:
    <<: *shared
    image: "ghcr.io/open-contracting/pelican-frontend-static:latest"
    ports:
      - {{ site.static_port }}:8080
{%- endif %}
