x-shared: &shared
  env_file: .env
  user: "{{ pillar.docker.uid }}:{{ pillar.docker.uid }}"
  extra_hosts:
    - "host.docker.internal:host-gateway"
  restart: unless-stopped

services:
  web:
    image: "ghcr.io/open-contracting/pelican-frontend-django:latest"
    ports:
      - {{ pillar.docker_apps.pelican_frontend.port }}:8000
{%- if 'reports' in pillar.docker_apps.pelican_frontend %}
    volumes:
      # The right-hand path must match the directory of the settings.SERVICE_ACCOUNT_JSON_FILE default value in pelican-frontend.
      - {{ pillar.docker_apps.pelican_frontend.host_dir }}:/data
  vue:
    image: "ghcr.io/open-contracting/pelican-frontend-vue:latest"
    ports:
      - {{ pillar.apache.sites.pelican_frontend.context.port }}:8080
{%- end %}
