services:
  web:
    env_file: .env
    image: "ghcr.io/open-contracting/pelican-frontend-django:latest"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - {{ pillar.docker_apps.pelican_frontend.port }}:8000
