x-shared: &shared
  env_file: .env
  user: "{{ pillar.docker.uid }}:{{ pillar.docker.uid }}"
  restart: unless-stopped

services:
  redis:
    image: rapidfort/redis-official:6.2-bookworm
    command: ["redis-server", "/redis.conf"]
    restart: always
    user: "{{ pillar.docker.uid }}:{{ pillar.docker.uid }}"
    healthcheck:
      test: redis-cli -h 127.0.0.1 ping | grep -q PONG
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - {{ directory }}/redis/data:/bitnami/redis/data
      - {{ directory }}/redis/redis.conf:/redis.conf
  web:
    <<: *shared
    image: "ghcr.io/open-contracting/bi.dream.gov.ua-qlikauth:latest"
    ports:
      - {{ site.qlikauth_port }}:3000
    volumes:
      - {{ directory }}/certs:/data/certs:ro
    depends_on:
      - redis
