# Based on: https://github.com/getnewdash/setup/blob/master/data/docker-compose.yml
x-shared: &shared
  image: redash/redash:10.1.0.b50633
  depends_on:
    - redis
  env_file: .env
  extra_hosts:
    - "host.docker.internal:host-gateway"
  restart: always

services:
  nginx:
    image: redash/nginx:latest
    ports:
      - "9090:80"
    depends_on:
      - server
    links:
      - server:redash
    volumes:
      - {{ directory }}/files/nginx-security.conf:/etc/nginx/conf.d/security.conf
    restart: always
  redis:
    image: bitnami/redis:7.2
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
  server:
    <<: *shared
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 1
  scheduler:
    <<: *shared
    command: scheduler
    depends_on:
      - server
  scheduled_worker:
    <<: *shared
    command: worker
    depends_on:
      - server
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *shared
    command: worker
    depends_on:
      - server
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 1
  worker:
    <<: *shared
    command: worker
    environment:
      QUEUES: "periodic,emails,default"
      WORKERS_COUNT: 1
