x-base: &base
  env_file: .env
  restart: unless-stopped
  user: "{{ pillar.docker.uid }}:{{ pillar.docker.uid }}"

x-shared: &shared
  <<: *base
  image: "ghcr.io/open-contracting/data-registry-django:latest"
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    # The right-hand path must match the settings.KINGFISHER_COLLECT_FILES_STORE default value in data-registry.
    - {{ pillar.kingfisher_collect.env.FILES_STORE }}:/data/collect
    # The right-hand path must match the settings.EXPORTER_DIR default value in data-registry.
    - {{ pillar.docker_apps.registry.exporter_host_dir }}:/data/exporter

services:
  web:
    <<: *shared
    ports: 
      - {{ pillar.docker_apps.registry.port }}:8000
  exporter:
    <<: *shared
    command: "python manage.py exporter"
  flattener:
    <<: *shared
    command: "python manage.py flattener"
  wiper:
    <<: *shared
    command: "python manage.py wiper"

  static:
    <<: *base
    image: "ghcr.io/open-contracting/data-registry-static:latest"
    ports:
      - {{ pillar.apache.sites.registry.context.static_port }}:8080
