x-shared: &shared
  env_file: .env
  user: "{{ pillar.docker.uid }}:{{ pillar.docker.uid }}"
  restart: unless-stopped

x-django: &django
  <<: *shared
  image: "ghcr.io/open-contracting/data-registry-django:latest"
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    # The right-hand path must match the settings.KINGFISHER_COLLECT_FILES_STORE default value in data-registry.
    - {{ pillar.kingfisher_collect.env.FILES_STORE }}:/data/collect
    # The right-hand path must match the settings.EXPORTER_DIR default value in data-registry.
    - {{ pillar.exporter_host_dir }}:/data/exporter

services:
  web:
    <<: *django
    ports:
      - {{ site.port }}:8000
  exporter:
    <<: *django
    command: "python manage.py exporter"
  flattener:
    <<: *django
    command: "python manage.py flattener"
  wiper:
    <<: *django
    command: "python manage.py wiper"
  cron:
    <<: *django
    profiles:
      - cron
  static:
    <<: *shared
    image: "ghcr.io/open-contracting/data-registry-static:latest"
    ports:
      - {{ site.static_port }}:8080
