x-shared: &shared
  env_file: .env
  image: "ghcr.io/open-contracting/data-registry-django:latest"
  restart: unless-stopped
  extra_hosts:
    - "host.docker.internal:host-gateway"
  # The right-hand path must match the settings.EXPORTER_DIR default value in data-registry.
  volumes:
    - /data/storage/exporter:/data/exporter

services:
  web:
    <<: *shared
    ports: 
      - {{ pillar.docker_apps.registry.port }}:8000
    # The right-hand path must match the settings.KINGFISHER_COLLECT_FILES_STORE default value in data-registry.
    volumes:
      - {{ pillar.kingfisher_collect.env.FILES_STORE }}:/data/collect
  exporter:
    <<: *shared
    command: "python manage.py exporter"
    scale: 2
  wiper:
    <<: *shared
    command: "python manage.py wiper"

  static:
    env_file: .env
    image: "ghcr.io/open-contracting/data-registry-static:latest"
    restart: unless-stopped
    ports:
      - {{ pillar.apache.sites.registry.context.static_port }}:8080
