x-env: &with-env
  env_file: .env
  restart: unless-stopped

x-user: &with-user
  <<: *with-env
  user: "{{ pillar.docker.uid }}:{{ pillar.docker.uid }}"

x-shared: &shared
  <<: *with-user
  image: "ghcr.io/open-contracting/spoonbill-web-django:latest"
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    # The right-hand path must match the settings.FILE_UPLOAD_TEMP_DIR default value in spoonbill-web.
    - {{ pillar.docker_apps.spoonbill.host_dir }}/tmp:/data/tmp
    # The right-hand path must match the settings.MEDIA_ROOT default value in spoonbill-web.
    - {{ pillar.docker_apps.spoonbill.host_dir }}/media:/data/media
    # The right-hand path must match the settings.DATAREGISTRY_MEDIA_ROOT default value in spoonbill-web.
    - {{ pillar.docker_apps.registry.exporter_host_dir }}:/data/exporter

services:
  traefik:
    <<: *with-env
    image: traefik:v2.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # https://hub.docker.com/_/traefik/
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./dynamic.toml:/etc/traefik/dynamic.toml
      - ./:/letsencrypt
    ports:
      - ${TRAEFIK_IP:-0.0.0.0}:80:80
      - ${TRAEFIK_IP:-0.0.0.0}:443:443
  redis:
    <<: *with-env
    hostname: redis
    image: bitnami/redis:latest
  app:
    <<: *shared
    hostname: app
    command: sh -c "daphne -b 0.0.0.0 -p 8000 spoonbill_web.asgi:application"
    depends_on:
      - traefik
      - redis
  celery_worker:
    <<: *shared
    command: celery -A spoonbill_web worker -l INFO --concurrency=4
    depends_on:
      - redis
      - app
  celery_beat:
    <<: *shared
    command: celery -A spoonbill_web beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - app
  front:
    image: ghcr.io/open-contracting/spoonbill-web-vue:latest
    depends_on:
      - app
    volumes:
      # The right-hand path must match the settings.MEDIA_ROOT default value in spoonbill-web.
      - {{ pillar.docker_apps.spoonbill.host_dir }}/media:/data/media
