x-shared: &shared
  env_file: .env
  user: "{{ pillar.docker.uid }}:{{ pillar.docker.uid }}"
  restart: unless-stopped

x-django: &django
  <<: *shared
  image: "ghcr.io/open-contracting/spoonbill-web-django:latest"
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    # The right-hand path must match the settings.FILE_UPLOAD_TEMP_DIR default value in spoonbill-web.
    - {{ entry.host_dir }}/tmp:/data/tmp
    # The right-hand path must match the settings.MEDIA_ROOT default value in spoonbill-web.
    - {{ entry.host_dir }}/media:/data/media
    # The right-hand path must match the settings.DATAREGISTRY_MEDIA_ROOT default value in spoonbill-web.
    - {{ pillar.exporter_host_dir }}:/data/exporter
  depends_on:
    - redis

services:
  redis:
    image: bitnamilegacy/redis:6.2
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli -h 127.0.0.1 ping | grep -q PONG
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - {{ entry.host_dir }}/redis/data:/bitnami/redis/data
      - {{ entry.host_dir }}/redis/tmp:/opt/bitnami/redis/tmp
  web:
    <<: *django
    ports:
      - {{ site.port }}:8000
  celery_worker:
    <<: *django
    command: celery -A core worker -l INFO --concurrency=4
  celery_beat:
    <<: *django
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
  static:
    <<: *shared
    image: "ghcr.io/open-contracting/spoonbill-web-static:latest"
    ports:
      - {{ site.static_port }}:8080
    volumes:
      # The right-hand path must match the settings.MEDIA_ROOT default value in spoonbill-web.
      - {{ entry.host_dir }}/media:/data/media
