name: OCDS Data Review Tool live tests
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *"
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.6
      - uses: actions/cache@v3
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Install
        run: |
          python -m venv venv
          . venv/bin/activate
          git clone 'https://github.com/open-contracting/cove-ocds.git'
          cd cove-ocds
          pip install -r requirements_dev.txt
          # Google Chrome and ChromeDriver are already included.
          # https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
      - name: Test
        run: |
          . venv/bin/activate
          cd cove-ocds
          CUSTOM_SERVER_URL=https://standard.open-contracting.org/ DJANGO_SETTINGS_MODULE=cove_project.settings py.test tests/test_functional.py
      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          server_address: ${{secrets.MAIL_HOST}}
          server_port: ${{secrets.MAIL_PORT}}
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: "GitHub Actions: ${{github.repository}} ${{github.workflow}} failed!"
          body: |
            GitHub Actions: ${{github.repository}} ${{github.workflow}} failed!

            ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
          to: inbox+opendataservices+443f+servers@plan.io, sysadmin@open-contracting.org
          from: Github action <noreply@noreply.open-contracting.org>
